versions:
  "1.0.3":
    folder: all

  "1.0.4":
    folder: all

  "1.1.0":
    folder: all

  "1.1.1":
    folder: all

  "1.1.2":
    folder: all

  "1.1.4":
    folder: all

  "1.1.5":
    folder: all
